-- shema.sql

-- Table reservation

CREATE TABLE IF NOT EXISTS reservation (
  id SERIAL PRIMARY KEY,
  full_name VARCHAR(255)NOT NULL,
  email VARCHAR(255) NOT NULL,
  date_rdv TIMESTAMP WITH TIME ZONE NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT now(),
);

-- Table newsletter

CREATE TABLE IF NOT EXISTS newsletter(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Table User
CREATE TABLE IF NOT EXISTS kongo_user(
  id SERIAL PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  numeroCarte VARCHAR(255) NOT NULL,
  createdAt TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updatedAt TIMESTAMP WITH TIME ZONE DEFAULT now()
);